defaults: &defaults
  adapter: mysql2
  username: root
  password: mygirl55
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  database: wikipedia
  <<: *defaults

test:
  database: wikipedia_test
  <<: *defaults
